services:
  claude:
    build:
      dockerfile: .devcontainer/Dockerfile
      args:
        TZ: ${TZ:-America/Los_Angeles}
        GIT_DELTA_VERSION: "0.18.2"
        ZSH_IN_DOCKER_VERSION: "1.2.0"
        USERNAME: "claude"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    user: claude
    working_dir: /workspace
    ports:
      - "8080:8080"
    volumes:
      - ./workspace:/workspace:delegated
      - ./claude-config:/claude-config:ro
      - asdf-state:/home/claude/.asdf
      - claude-code-bashhistory:/commandhistory
      - claude-code-config:/home/claude/.claude
    environment:
      - DOCKER_HOST=socat:2375
    stdin_open: true
    tty: true
    networks:
      - local-mcp-servers_agents
  socat:
    image: alpine/socat
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - local-mcp-servers_agents

secrets:
  github_api_key:
    environment: CLAUDE_GH_API_KEY

volumes:
  claude-code-bashhistory:
  claude-code-config:
  asdf-state:

networks:
  local-mcp-servers_agents:
    external: true
